<a href="https://colab.research.google.com/github/iamhardyyy/git-demo2/blob/main/Next%20Word%20prediction%20using%20bidirectional%20LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import os

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,LSTM,Dense,Bidirectional
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/medium_data.csv')
data

,id,url,title,subtitle,image,claps,responses,reading_time,publication,date
0,1,https://towardsdatascience.com/a-beginners-gui...,A Beginner’s Guide to Word Embedding with Gens...,NaN,1.png,850,8,8,Towards Data Science,2019-05-30
1,2,https://towardsdatascience.com/hands-on-graph-...,Hands-on Graph Neural Networks with PyTorch & ...,NaN,2.png,1100,11,9,Towards Data Science,2019-05-30
2,3,https://towardsdatascience.com/how-to-use-ggpl...,How to Use ggplot2 in Python,A Grammar of Graphics for Python,3.png,767,1,5,Towards Data Science,2019-05-30
3,4,https://towardsdatascience.com/databricks-how-...,Databricks: How to Save Files in CSV on Your L...,When I work on Python projects dealing…,4.jpeg,354,0,4,Towards Data Science,2019-05-30
4,5,https://towardsdatascience.com/a-step-by-step-...,A Step-by-Step Implementation of Gradient Desc...,One example of building neural…,5.jpeg,211,3,4,Towards Data Science,2019-05-30
...,...,...,...,...,...,...,...,...,...,...
6503,6504,https://medium.com/better-marketing/we-vs-i-ho...,“We” vs “I” — How Should You Talk About Yourse...,Basic copywriting choices with a big…,6504.jpg,661,6,6,Better Marketing,2019-12-05
6504,6505,https://medium.com/better-marketing/how-donald...,How Donald Trump Markets Himself,Lessons from who might be the most popular bra...,6505.jpeg,189,1,5,Better Marketing,2019-12-05
6505,6506,https://medium.com/better-marketing/content-an...,Content and Marketing Beyond Mass Consumption,How to acquire customers without wasting money...,6506.jpg,207,1,8,Better Marketing,2019-12-05
6506,6507,https://medium.com/better-marketing/5-question...,5 Questions All Copywriters Should Ask Clients...,Save time and effort by…,6507.jpg,253,2,5,Better Marketing,2019-12-05
6507,6508,https://medium.com/better-marketing/how-to-wri...,How To Write a Good Business Blog Post,An A-to-Z guide for non-writers,6508.jpg,147,0,9,Better Marketing,2019-12-05

In [ ]:
data['title']

0       A Beginner’s Guide to Word Embedding with Gens...
1       Hands-on Graph Neural Networks with PyTorch & ...
2                            How to Use ggplot2 in Python
3       Databricks: How to Save Files in CSV on Your L...
4       A Step-by-Step Implementation of Gradient Desc...
                              ...
6503    “We” vs “I” — How Should You Talk About Yourse...
6504                     How Donald Trump Markets Himself
6505        Content and Marketing Beyond Mass Consumption
6506    5 Questions All Copywriters Should Ask Clients...
6507               How To Write a Good Business Blog Post
Name: title, Length: 6508, dtype: object

In [ ]:
data['title']=data['title'].apply(lambda x:x.replace(u'\xa0',u''))
data['title']=data['title'].apply(lambda x:x.replace('\u200a',''))

In [ ]:
tokenize=Tokenizer()
tokenize.fit_on_texts(data['title'])
total_words=len(tokenize.word_index)+1
total_words

10863

In [ ]:
input_num= []
for line in data['title']:
    token = tokenize.texts_to_sequences([line])[0]
    #print(token_list)

    for i in range(1, len(token)):
        n_gram = token[:i+1]
        input_num.append(n_gram)

print(input_num)
print("Total input sequences: ", len(input_num))

[[4, 565], [4, 565, 60], [4, 565, 60, 1], [4, 565, 60, 1, 434], [4, 565, 60, 1, 434, 1311], [4, 565, 60, 1, 434, 1311, 14], [4, 565, 60, 1, 434, 1311, 14, 3517], [4, 565, 60, 1, 434, 1311, 14, 3517, 3518], [3519, 21], [3519, 21, 783], [3519, 21, 783, 111], [3519, 21, 783, 111, 146], [3519, 21, 783, 111, 146, 14], [3519, 21, 783, 111, 146, 14, 476], [3519, 21, 783, 111, 146, 14, 476, 476], [3519, 21, 783, 111, 146, 14, 476, 476, 1654], [5, 1], [5, 1, 62], [5, 1, 62, 3520], [5, 1, 62, 3520, 193], [3521, 5], [3521, 5, 1], [3521, 5, 1, 232], [3521, 5, 1, 232, 1079], [3521, 5, 1, 232, 1079, 10], [3521, 5, 1, 232, 1079, 10, 2220], [3521, 5, 1, 232, 1079, 10, 2220, 21], [3521, 5, 1, 232, 1079, 10, 2220, 21, 9], [3521, 5, 1, 232, 1079, 10, 2220, 21, 9, 3522], [4, 170], [4, 170, 63], [4, 170, 63, 170], [4, 170, 63, 170, 400], [4, 170, 63, 170, 400, 6], [4, 170, 63, 170, 400, 6, 3523], [4, 170, 63, 170, 400, 6, 3523, 2221], [4, 170, 63, 170, 400, 6, 3523, 2221, 7], [4, 170, 63, 170, 400, 6, 3523, 2221, 7, 1312], [23, 243], [23, 243, 100], [23, 243, 100, 1], [23, 243, 100, 1, 401], [23, 243, 100, 1, 401, 11], [23, 243, 100, 1, 401, 11, 18], [23, 243, 100, 1, 401, 11, 18, 268], [1313, 295], [1313, 295, 3524], [100, 1], [100, 1, 3525], [100, 1, 3525, 784], [100, 1, 3525, 784, 2222], [100, 1, 3525, 784, 2222, 629], [100, 1, 3525, 784, 2222, 629, 281], [331, 435], [331, 435, 1655], [331, 435, 1655, 13], [331, 435, 1655, 13, 2], [331, 435, 1655, 13, 2, 71], [331, 435, 1655, 13, 2, 71, 3526], [20, 69], [20, 69, 45], [20, 69, 45, 109], [20, 69, 45, 109, 131], [20, 69, 45, 109, 131, 3527], [82, 15], [82, 15, 8], [82, 15, 8, 82], [82, 15, 8, 82, 8], [82, 15, 8, 82, 8, 16], [82, 15, 8, 82, 8, 16, 82], [82, 15, 8, 82, 8, 16, 82, 20], [82, 15, 8, 82, 8, 16, 82, 20, 19], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296, 58], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296, 58, 908], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296, 58, 908, 3528], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296, 58, 908, 3528, 3529], [82, 15, 8, 82, 8, 16, 82, 20, 19, 92, 22, 296, 58, 908, 3528, 3529, 82], [101, 4], [101, 4, 3530], [101, 4, 3530, 566], [101, 4, 3530, 566, 2223], [98, 4], [98, 4, 3531], [98, 4, 3531, 1656], [98, 4, 3531, 1656, 3532], [5, 1], [5, 1, 3533], [909, 2224], [909, 2224, 11], [909, 2224, 11, 222], [909, 2224, 11, 222, 165], [5, 1], [5, 1, 630], [5, 1, 630, 2225], [5, 1, 630, 2225, 477], [297, 32], [297, 32, 3534], [297, 32, 3534, 11], [297, 32, 3534, 11, 3535], [3536, 3537], [3536, 3537, 47], [3536, 3537, 47, 2226], [3536, 3537, 47, 2226, 2227], [3536, 3537, 47, 2226, 2227, 7], [3536, 3537, 47, 2226, 2227, 7, 4], [3536, 3537, 47, 2226, 2227, 7, 4, 2226], [3536, 3537, 47, 2226, 2227, 7, 4, 2226, 629], [18, 61], [18, 61, 315], [18, 61, 315, 269], [910, 436], [910, 436, 11], [910, 436, 11, 698], [910, 436, 11, 698, 1657], [3538, 3539], [3538, 3539, 911], [3538, 3539, 911, 88], [3538, 3539, 911, 88, 912], [3538, 3539, 911, 88, 912, 26], [3538, 3539, 911, 88, 912, 26, 3540], [3538, 3539, 911, 88, 912, 26, 3540, 2], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39, 24], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39, 24, 25], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39, 24, 25, 124], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39, 24, 25, 124, 1], [3538, 3539, 911, 88, 912, 26, 3540, 2, 567, 5, 39, 24, 25, 124, 1, 2228], [2229, 6], [2229, 6, 2230], [2229, 6, 2230, 1314], [2229, 6, 2230, 1314, 3541], [2229, 6, 2230, 1314, 3541, 6], [2229, 6, 2230, 1314, 3541, 6, 3542], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543, 349], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543, 349, 3544], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543, 349, 3544, 7], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543, 349, 3544, 7, 349], [2229, 6, 2230, 1314, 3541, 6, 3542, 3543, 349, 3544, 7, 349, 3545], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 5], [3, 15, 8, 3, 8, 16, 3, 5, 18], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244, 400], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244, 400, 6], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244, 400, 6, 1080], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244, 400, 6, 1080, 3546], [3, 15, 8, 3, 8, 16, 3, 5, 18, 282, 785, 1658, 4, 244, 400, 6, 1080, 3546, 3], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 1081], [3, 15, 8, 3, 8, 16, 3, 1081, 21], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231, 7], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231, 7, 1659], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231, 7, 1659, 6], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231, 7, 1659, 6, 2232], [3, 15, 8, 3, 8, 16, 3, 1081, 21, 786, 52, 786, 21, 1081, 2, 2231, 7, 1659, 6, 2232, 3], [31, 11], [31, 11, 128], [31, 11, 128, 184], [31, 11, 128, 184, 4], [31, 11, 128, 184, 4, 40], [31, 11, 128, 184, 4, 40, 170], [31, 11, 128, 184, 4, 40, 170, 155], [31, 11, 128, 184, 4, 40, 170, 155, 3547], [3548, 13], [3548, 13, 23], [3548, 13, 23, 165], [3548, 13, 23, 165, 33], [3548, 13, 23, 165, 33, 4], [3548, 13, 23, 165, 33, 4, 61], [3548, 13, 23, 165, 33, 4, 61, 3549], [3548, 13, 23, 165, 33, 4, 61, 3549, 31], [3548, 13, 23, 165, 33, 4, 61, 3549, 31, 120], [283, 10], [283, 10, 31], [283, 10, 31, 2233], [913, 2234], [913, 2234, 914], [913, 2234, 914, 1082], [20, 270], [20, 270, 13], [20, 270, 13, 9], [20, 270, 13, 9, 3550], [568, 36], [568, 36, 1660], [568, 36, 1660, 5], [568, 36, 1660, 5, 37], [568, 36, 1660, 5, 37, 3551], [568, 36, 1660, 5, 37, 3551, 2235], [568, 36, 1660, 5, 37, 3551, 2235, 3552], [5, 19], [5, 19, 92], [5, 19, 92, 1], [5, 19, 92, 1, 28], [5, 19, 92, 1, 28, 48], [5, 19, 92, 1, 28, 48, 245], [5, 19, 92, 1, 28, 48, 245, 57], [5, 19, 92, 1, 28, 48, 245, 57, 96], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6, 699], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6, 699, 2236], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6, 699, 2236, 1315], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6, 699, 2236, 1315, 222], [5, 19, 92, 1, 28, 48, 245, 57, 96, 6, 699, 2236, 1315, 222, 3553], [1661, 700], [1661, 700, 631], [1661, 700, 631, 520], [1661, 700, 631, 520, 7], [1661, 700, 631, 520, 7, 632], [1661, 700, 631, 520, 7, 632, 1316], [98, 298], [98, 298, 701], [98, 298, 701, 3554], [98, 298, 701, 3554, 11], [98, 298, 701, 3554, 11, 93], [98, 298, 701, 3554, 11, 93, 32], [98, 298, 701, 3554, 11, 93, 32, 478], [136, 4], [136, 4, 222], [136, 4, 222, 1083], [136, 4, 222, 1083, 2237], [47, 75], [47, 75, 11], [47, 75, 11, 244], [47, 75, 11, 244, 2238], [26, 2239], [26, 2239, 3555], [26, 2239, 3555, 38], [26, 2239, 3555, 38, 569], [26, 2239, 3555, 38, 569, 1317], [19, 132], [19, 132, 2240], [19, 132, 2240, 479], [19, 132, 2240, 479, 27], [19, 132, 2240, 479, 27, 149], [19, 132, 2240, 479, 27, 149, 160], [19, 132, 2240, 479, 27, 149, 160, 20], [19, 132, 2240, 479, 27, 149, 160, 20, 1662], [3556, 13], [3556, 13, 2], [3556, 13, 2, 94], [3556, 13, 2, 94, 3557], [3556, 13, 2, 94, 3557, 521], [3556, 13, 2, 94, 3557, 521, 11], [3556, 13, 2, 94, 3557, 521, 11, 1084], [3556, 13, 2, 94, 3557, 521, 11, 1084, 9], [3556, 13, 2, 94, 3557, 521, 11, 1084, 9, 3558], [5, 1], [5, 1, 2241], [5, 1, 2241, 48], [5, 1, 2241, 48, 22], [5, 1, 2241, 48, 22, 2], [5, 1, 2241, 48, 22, 2, 316], [5, 1, 2241, 48, 22, 2, 316, 3559], [633, 3560], [633, 3560, 14], [633, 3560, 14, 3561], [3562, 4], [3562, 4, 2242], [3562, 4, 2242, 271], [3562, 4, 2242, 271, 10], [3562, 4, 2242, 271, 10, 23], [3562, 4, 2242, 271, 10, 23, 698], [3562, 4, 2242, 271, 10, 23, 698, 140], [256, 44], [256, 44, 23], [256, 44, 23, 3563], [787, 4], [787, 4, 2243], [787, 4, 2243, 350], [49, 1318], [49, 1318, 1319], [49, 1318, 1319, 1320], [49, 1318, 1319, 1320, 1], [49, 1318, 1319, 1320, 1, 3564], [49, 1318, 1319, 1320, 1, 3564, 915], [788, 14], [788, 14, 246], [788, 14, 246, 1], [788, 14, 246, 1, 171], [788, 14, 246, 1, 171, 1321], [2244, 10], [2244, 10, 257], [53, 3565], [53, 3565, 570], [53, 3565, 570, 54], [53, 3565, 570, 54, 4], [53, 3565, 570, 54, 4, 141], [53, 3565, 570, 54, 4, 141, 10], [53, 3565, 570, 54, 4, 141, 10, 3566], [223, 34], [223, 34, 7], [223, 34, 7, 5], [223, 34, 7, 5, 1], [223, 34, 7, 5, 1, 1663], [223, 34, 7, 5, 1, 1663, 402], [121, 55], [121, 55, 1], [121, 55, 1, 522], [121, 55, 1, 522, 9], [121, 55, 1, 522, 9, 916], [121, 55, 1, 522, 9, 916, 1085], [121, 55, 1, 522, 9, 916, 1085, 21], [121, 55, 1, 522, 9, 916, 1085, 21, 207], [161, 55], [161, 55, 137], [161, 55, 137, 480], [161, 55, 137, 480, 702], [161, 55, 137, 480, 702, 403], [161, 55, 137, 480, 702, 403, 523], [161, 55, 137, 480, 702, 403, 523, 38], [161, 55, 137, 480, 702, 403, 523, 38, 2245], [1322, 200], [1322, 200, 4], [1322, 200, 4, 3567], [1322, 200, 4, 3567, 156], [1322, 200, 4, 3567, 156, 3568], [147, 3569], [147, 3569, 917], [147, 3569, 917, 380], [147, 3569, 917, 380, 918], [147, 3569, 917, 380, 918, 33], [147, 3569, 917, 380, 918, 33, 524], [147, 3569, 917, 380, 918, 33, 524, 3570], [2, 2246], [2, 2246, 65], [2, 2246, 65, 3571], [4, 83], [4, 83, 3572], [3573, 1086], [3573, 1086, 481], [3573, 1086, 481, 14], [3573, 1086, 481, 14, 3574], [3573, 1086, 481, 14, 3574, 571], [3573, 1086, 481, 14, 3574, 571, 3575], [3576, 131], [3576, 131, 122], [3576, 131, 122, 919], [3576, 131, 122, 919, 3577], [17, 1323], [17, 1323, 123], [17, 1323, 123, 93], [17, 1323, 123, 93, 1], [17, 1323, 123, 93, 1, 572], [17, 1323, 123, 93, 1, 572, 3578], [17, 1323, 123, 93, 1, 572, 3578, 7], [17, 1323, 123, 93, 1, 572, 3578, 7, 2247], [17, 1323, 123, 93, 1, 572, 3578, 7, 2247, 162], [17, 1323, 123, 93, 1, 572, 3578, 7, 2247, 162, 3579], [17, 1323, 123, 93, 1, 572, 3578, 7, 2247, 162, 3579, 3580], [3581, 3582], [437, 525], [437, 525, 2], [437, 525, 2, 3583], [17, 19], [17, 19, 224], [17, 19, 224, 27], [17, 19, 224, 27, 2248], [17, 19, 224, 27, 2248, 438], [17, 19, 224, 27, 2248, 438, 10], [17, 19, 224, 27, 2248, 438, 10, 634], [17, 19, 224, 27, 2248, 438, 10, 634, 6], [17, 19, 224, 27, 2248, 438, 10, 634, 6, 2249], [2, 58], [2, 58, 19], [2, 58, 19, 247], [2, 58, 19, 247, 3584], [2, 58, 19, 247, 3584, 63], [2, 58, 19, 247, 3584, 63, 1664], [2, 58, 19, 247, 3584, 63, 1664, 1665], [1087, 3585], [1087, 3585, 526], [1087, 3585, 526, 3586], [1087, 3585, 526, 3586, 7], [1087, 3585, 526, 3586, 7, 3587], [635, 3588], [635, 3588, 13], [635, 3588, 13, 38], [635, 3588, 13, 38, 2], [635, 3588, 13, 38, 2, 3589], [635, 3588, 13, 38, 2, 3589, 1666], [635, 3588, 13, 38, 2, 3589, 1666, 3590], [4, 351], [4, 351, 11], [4, 351, 11, 317], [3591, 13], [3591, 13, 1664], [3591, 13, 1664, 3592], [9, 482], [9, 482, 3593], [9, 482, 3593, 21], [9, 482, 3593, 21, 5], [9, 482, 3593, 21, 5, 12], [9, 482, 3593, 21, 5, 12, 352], [9, 482, 3593, 21, 5, 12, 352, 9], [9, 482, 3593, 21, 5, 12, 352, 9, 1324], [19, 247], [19, 247, 2250], [19, 247, 2250, 44], [19, 247, 2250, 44, 4], [19, 247, 2250, 44, 4, 3594], [19, 247, 2250, 44, 4, 3594, 527], [19, 247, 2250, 44, 4, 3594, 527, 332], [19, 247, 2250, 44, 4, 3594, 527, 332, 3595], [299, 1], [299, 1, 2], [299, 1, 2, 567], [299, 1, 2, 567, 14], [299, 1, 2, 567, 14, 3596], [299, 1, 2, 567, 14, 3596, 2251], [17, 1661], [17, 1661, 3597], [17, 1661, 3597, 59], [17, 1661, 3597, 59, 9], [17, 1661, 3597, 59, 9, 194], [17, 1661, 3597, 59, 9, 194, 1], [17, 1661, 3597, 59, 9, 194, 1, 2], [17, 1661, 3597, 59, 9, 194, 1, 2, 1667], [17, 1661, 3597, 59, 9, 194, 1, 2, 1667, 3598], [223, 573], [223, 573, 12], [223, 573, 12, 56], [223, 573, 12, 56, 36], [223, 573, 12, 56, 36, 36], [223, 573, 12, 56, 36, 36, 13], [223, 573, 12, 56, 36, 36, 13, 150], [223, 573, 12, 56, 36, 36, 13, 150, 1088], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185, 36], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185, 36, 13], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185, 36, 13, 117], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185, 36, 13, 117, 4], [223, 573, 12, 56, 36, 36, 13, 150, 1088, 23, 3599, 1, 2252, 185, 36, 13, 117, 4, 3600], [37, 86], [37, 86, 46], [37, 86, 46, 2253], [3601, 13], [3601, 13, 2], [3601, 13, 2, 94], [3601, 13, 2, 94, 172], [3601, 13, 2, 94, 172, 3602], [2254, 5], [2254, 5, 19], [2254, 5, 19, 439], [2254, 5, 19, 439, 2255], [2254, 5, 19, 439, 2255, 42], [2254, 5, 19, 439, 2255, 42, 1], [2254, 5, 19, 439, 2255, 42, 1, 27], [2254, 5, 19, 439, 2255, 42, 1, 27, 3603], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 131], [3, 15, 8, 3, 8, 16, 3, 131, 3604], [3, 15, 8, 3, 8, 16, 3, 131, 3604, 5], [3, 15, 8, 3, 8, 16, 3, 131, 3604, 5, 25], [3, 15, 8, 3, 8, 16, 3, 131, 3604, 5, 25, 185], [3, 15, 8, 3, 8, 16, 3, 131, 3604, 5, 25, 185, 124], [3, 15, 8, 3, 8, 16, 3, 131, 3604, 5, 25, 185, 124, 3], [3605, 5], [3605, 5, 3606], [3605, 5, 3606, 3607], [3605, 5, 3606, 3607, 10], [3605, 5, 3606, 3607, 10, 1325], [482, 102], [482, 102, 2256], [201, 14], [201, 14, 2], [201, 14, 2, 3608], [201, 14, 2, 3608, 10], [201, 14, 2, 3608, 10, 3609], [160, 17], [160, 17, 12], [160, 17, 12, 43], [160, 17, 12, 43, 195], [160, 17, 12, 43, 195, 2257], [160, 17, 12, 43, 195, 2257, 2], [160, 17, 12, 43, 195, 2257, 2, 636], [160, 17, 12, 43, 195, 2257, 2, 636, 6], [160, 17, 12, 43, 195, 2257, 2, 636, 6, 440], [5, 1], [5, 1, 2258], [5, 1, 2258, 9], [5, 1, 2258, 9, 3610], [5, 1, 2258, 9, 3610, 1], [5, 1, 2258, 9, 3610, 1, 2], [5, 1, 2258, 9, 3610, 1, 2, 2259], [5, 1, 2258, 9, 3610, 1, 2, 2259, 920], [483, 102], [483, 102, 333], [483, 102, 333, 102], [483, 102, 333, 102, 3611], [483, 102, 333, 102, 3611, 86], [483, 102, 333, 102, 3611, 86, 161], [483, 102, 333, 102, 3611, 86, 161, 1], [483, 102, 333, 102, 3611, 86, 161, 1, 441], [483, 102, 333, 102, 3611, 86, 161, 1, 441, 3612], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 2], [3, 15, 8, 3, 8, 16, 3, 2, 1326], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574, 1668], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574, 1668, 1], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574, 1668, 1, 2260], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574, 1668, 1, 2260, 1669], [3, 15, 8, 3, 8, 16, 3, 2, 1326, 3613, 574, 1668, 1, 2260, 1669, 3], [17, 12], [17, 12, 46], [17, 12, 46, 1], [17, 12, 46, 1, 77], [17, 12, 46, 1, 77, 1670], [17, 12, 46, 1, 77, 1670, 38], [17, 12, 46, 1, 77, 1670, 38, 3614], [5, 1], [5, 1, 404], [5, 1, 404, 3615], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 703], [3, 15, 8, 3, 8, 16, 3, 703, 10], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704, 7], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704, 7, 3616], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704, 7, 3616, 22], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704, 7, 3616, 22, 1671], [3, 15, 8, 3, 8, 16, 3, 703, 10, 9, 704, 7, 3616, 22, 1671, 3], [528, 1089], [528, 1089, 102], [528, 1089, 102, 3617], [3618, 3619], [3618, 3619, 13], [3618, 3619, 13, 3620], [3618, 3619, 13, 3620, 7], [3618, 3619, 13, 3620, 7, 915], [17, 12], [17, 12, 334], [17, 12, 334, 62], [17, 12, 334, 62, 789], [17, 12, 334, 62, 789, 11], [17, 12, 334, 62, 789, 11, 575], [17, 2], [17, 2, 173], [17, 2, 173, 3621], [17, 2, 173, 3621, 318], [17, 2, 173, 3621, 318, 232], [17, 2, 173, 3621, 318, 232, 2261], [248, 65], [248, 65, 1672], [248, 65, 1672, 196], [248, 65, 1672, 196, 4], [248, 65, 1672, 196, 4, 1327], [248, 65, 1672, 196, 4, 1327, 10], [248, 65, 1672, 196, 4, 1327, 10, 3622], [5, 1], [5, 1, 1673], [5, 1, 1673, 442], [5, 1, 1673, 442, 1], [5, 1, 1673, 442, 1, 4], [5, 1, 1673, 442, 1, 4, 3623], [705, 9], [705, 9, 174], [705, 9, 174, 21], [705, 9, 174, 21, 3624], [47, 790], [47, 790, 1], [47, 790, 1, 3625], [47, 790, 1, 3625, 706], [47, 790, 1, 3625, 706, 3626], [2, 791], [2, 791, 11], [2, 791, 11, 4], [2, 791, 11, 4, 67], [2, 791, 11, 4, 67, 3627], [2, 791, 11, 4, 67, 3627, 11], [2, 791, 11, 4, 67, 3627, 11, 18], [2, 791, 11, 4, 67, 3627, 11, 18, 268], [23, 100], [23, 100, 1], [23, 100, 1, 66], [23, 100, 1, 66, 3628], [2262, 2], [2262, 2, 707], [2262, 2, 707, 58], [2262, 2, 707, 58, 3629], [5, 1], [5, 1, 405], [5, 1, 405, 10], [5, 1, 405, 10, 2], [5, 1, 405, 10, 2, 1667], [5, 1, 405, 10, 2, 1667, 7], [5, 1, 405, 10, 2, 1667, 7, 41], [5, 1, 405, 10, 2, 1667, 7, 41, 9], [5, 1, 405, 10, 2, 1667, 7, 41, 9, 3630], [215, 2263], [215, 2263, 3631], [1674, 21], [1674, 21, 3632], [1674, 21, 3632, 2264], [1674, 21, 3632, 2264, 27], [1674, 21, 3632, 2264, 27, 186], [1674, 21, 3632, 2264, 27, 186, 21], [1674, 21, 3632, 2264, 27, 186, 21, 3633], [19, 49], [19, 49, 80], [19, 49, 80, 20], [19, 49, 80, 20, 1], [19, 49, 80, 20, 1, 30], [19, 49, 80, 20, 1, 30, 14], [19, 49, 80, 20, 1, 30, 14, 3634], [47, 75], [47, 75, 11], [47, 75, 11, 3635], [47, 75, 11, 3635, 1], [47, 75, 11, 3635, 1, 67], [47, 75, 11, 3635, 1, 67, 319], [47, 75, 11, 3635, 1, 67, 319, 34], [47, 75, 11, 3635, 1, 67, 319, 34, 2265], [2, 1090], [2, 1090, 6], [2, 1090, 6, 3636], [2, 1090, 6, 3636, 524], [2, 1090, 6, 3636, 524, 175], [2, 1090, 6, 3636, 524, 175, 1675], [2, 1090, 6, 3636, 524, 175, 1675, 443], [2, 1090, 6, 3636, 524, 175, 1675, 443, 708], [2, 1090, 6, 3636, 524, 175, 1675, 443, 708, 2266], [43, 12], [43, 12, 2267], [43, 12, 2267, 2], [43, 12, 2267, 2, 3637], [2268, 574], [2268, 574, 5], [2268, 574, 5, 137], [2268, 574, 5, 137, 13], [2268, 574, 5, 137, 13, 3638], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 129], [3, 15, 8, 3, 8, 16, 3, 129, 1091], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41, 7], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41, 7, 3639], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41, 7, 3639, 166], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41, 7, 3639, 166, 1092], [3, 15, 8, 3, 8, 16, 3, 129, 1091, 22, 176, 61, 1, 41, 7, 3639, 166, 1092, 3], [5, 1], [5, 1, 28], [5, 1, 28, 1093], [5, 1, 28, 1093, 57], [5, 1, 28, 1093, 57, 225], [130, 284], [130, 284, 57], [130, 284, 57, 4], [130, 284, 57, 4, 3640], [130, 284, 57, 4, 3640, 1328], [130, 284, 57, 4, 3640, 1328, 3641], [3, 15], [3, 15, 8], [3, 15, 8, 3], [3, 15, 8, 3, 8], [3, 15, 8, 3, 8, 16], [3, 15, 8, 3, 8, 16, 3], [3, 15, 8, 3, 8, 16, 3, 26], [3, 15, 8, 3, 8, 16, 3, 26, 37], [3, 15, 8, 3, 8, 16, 3, 26, 3

In [ ]:
max_len=max([len(x) for x in input_num])

input_num = np.array(pad_sequences(input_num, maxlen=max_len, padding='pre'))
input_num[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   4, 565,  60],
      dtype=int32)

In [ ]:
xs=input_num[:,:-1]
label=input_num[:,-1]
ys=tf.keras.utils.to_categorical(label,num_classes=total_words)

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_len-1))
model.add(Bidirectional(LSTM(150)))
model.add(Dense(total_words, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
word = model.fit(xs, ys, epochs=60, verbose=1)
print(model)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 25s 13ms/step - accuracy: 0.0818 - loss: 7.4619
Epoch 2/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.1299 - loss: 6.6191
Epoch 3/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.1531 - loss: 6.0571
Epoch 4/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.1749 - loss: 5.5111
Epoch 5/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.1949 - loss: 4.9753
Epoch 6/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - accuracy: 0.2260 - loss: 4.4688
Epoch 7/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.2764 - loss: 4.0021
Epoch 8/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.3421 - loss: 3.5667
Epoch 9/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.4062 - loss: 3.1732
Epoch 10/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 20s 13ms/step - accuracy: 0.4646 - loss: 2.8267
Epoch 11/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.5153 - loss: 2.5242
Epoch 12/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.5623 - loss: 2.2662
Epoch 13/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.6023 - loss: 2.0411
Epoch 14/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.6420 - loss: 1.8448
Epoch 15/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.6751 - loss: 1.6709
Epoch 16/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.7009 - loss: 1.5224
Epoch 17/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.7282 - loss: 1.3911
Epoch 18/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.7484 - loss: 1.2767
Epoch 19/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.7661 - loss: 1.1784
Epoch 20/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.7806 - loss: 1.0934
Epoch 21/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.7933 - loss: 1.0231
Epoch 22/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8044 - loss: 0.9612
Epoch 23/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8116 - loss: 0.9103
Epoch 24/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 20s 13ms/step - accuracy: 0.8187 - loss: 0.8669
Epoch 25/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8250 - loss: 0.8296
Epoch 26/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8282 - loss: 0.7985
Epoch 27/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8318 - loss: 0.7725
Epoch 28/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8330 - loss: 0.7520
Epoch 29/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8336 - loss: 0.7341
Epoch 30/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8357 - loss: 0.7173
Epoch 31/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8367 - loss: 0.7047
Epoch 32/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8375 - loss: 0.6921
Epoch 33/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8388 - loss: 0.6831
Epoch 34/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8386 - loss: 0.6758
Epoch 35/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8385 - loss: 0.6659
Epoch 36/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8396 - loss: 0.6620
Epoch 37/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8399 - loss: 0.6560
Epoch 38/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8402 - loss: 0.6496
Epoch 39/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8401 - loss: 0.6448
Epoch 40/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8398 - loss: 0.6432
Epoch 41/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8399 - loss: 0.6398
Epoch 42/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8399 - loss: 0.6365
Epoch 43/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8399 - loss: 0.6338
Epoch 44/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8404 - loss: 0.6307
Epoch 45/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8401 - loss: 0.6280
Epoch 46/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8399 - loss: 0.6263
Epoch 47/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 14ms/step - accuracy: 0.8397 - loss: 0.6256
Epoch 48/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8402 - loss: 0.6207
Epoch 49/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8408 - loss: 0.6201
Epoch 50/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8397 - loss: 0.6193
Epoch 51/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8406 - loss: 0.6169
Epoch 52/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8407 - loss: 0.6156
Epoch 53/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 21s 14ms/step - accuracy: 0.8397 - loss: 0.6161
Epoch 54/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8404 - loss: 0.6141
Epoch 55/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8403 - loss: 0.6120
Epoch 56/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8408 - loss: 0.6112
Epoch 57/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8412 - loss: 0.6102
Epoch 58/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8403 - loss: 0.6088
Epoch 59/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.8411 - loss: 0.6072
Epoch 60/60
1358/1358 ━━━━━━━━━━━━━━━━━━━━ 19s 14ms/step - accuracy: 0.8401 - loss: 0.6068
<Sequential name=sequential, built=True>

In [ ]:
text = input('enter the word :')
next_words =int(input('number of words to be predicted :'))

for _ in range(next_words):
    token_list = tokenize.texts_to_sequences([text])[0]
    token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')
    predictions = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predictions[0])
    output_word = tokenize.index_word.get(predicted_index, '')
    text += " " + output_word

print(text)

enter the word :deep
number of words to be predicted :5
deep learning for clinical diagnostics classification

In [ ]:
import pickle, json

os.makedirs('model', exist_ok=True)

model.save('model/lstm_model.h5')
pickle.dump(tokenize, open('model/tokenizer.pkl', 'wb'))
json.dump({'max_len': max_len}, open('model/config.json', 'w'))

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
import keras
print(keras.__version__)

3.13.2